name: Criar Branches para Membros do Time

on:
  workflow_dispatch:
    inputs:
      team_slug:
        description: 'Slug do Time do GitHub (ex: desenvolvimento)'
        required: true
        type: string
      organization:
        description: 'Nome da Organização do GitHub'
        required: true
        type: string
      base_branch:
        description: 'Branch base para criar os novos branches (opcional, padrão: main)'
        required: false
        type: string
        default: main

jobs:
  criar_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Configurar GitHub CLI
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('GH_TOKEN', '${{ secrets.GITHUB_TOKEN }}')

      - name: Obter membros do time
        id: get_team_members
        run: |
          ORG="${{ github.event.inputs.organization }}"
          TEAM_SLUG="${{ github.event.inputs.team_slug }}"
          API_URL="https://api.github.com/orgs/$ORG/teams/$TEAM_SLUG/members"

          echo "Buscando membros do time: $TEAM_SLUG na organização: $ORG"
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL")

          echo "::set-output name=members::$response"

      - name: Criar branches para cada membro
        run: |
          MEMBERS_JSON="${{ steps.get_team_members.outputs.members }}"
          echo "JSON dos membros: $MEMBERS_JSON"
          MEMBERS=$(echo "$MEMBERS_JSON" | jq -c '.[]')

          while IFS= read -r MEMBER; do
            LOGIN=$(echo "$MEMBER" | jq -r .login)
            BRANCH_NAME="team-${LOGIN}"
            echo "Criando branch: $BRANCH_NAME"
            gh branch "$BRANCH_NAME"
            git push origin "$BRANCH_NAME"
          done <<< "$MEMBERS"
